### ISSUE TITLE
tournaments_show_events only returns names

### ISSUE THREAD

**Issue by LuNoX** [PeterCat12/pysmash#23]
tournament_show_events function only returns the names. I'm not sure if this is intended but this approach is different from all other show_ methods where you get all data (including id which is kinda important)

**Comment by PeterCat12** [comment]
you can do something like... 
 `smash.tournament_show('hidden-bosses-4-0', ['event'])` to return tournament metaData along with a list of events. The original intent for the `tournament_show` method was to take in the tournament name, as well as the different valid params to return the appropriate meta data with specific param info. I will document this... 

I can see an argument though, that there NOW exists an inconsistent API contract... I will keep that new endpoint, but probably name it something different to avoid confusion... 

thoughts?

**Comment by LuNoX** [comment]
As long as it is consistent and you document it once it's done I'm fine with everything

**Comment by PeterCat12** [comment]
Cool. I will have a lot of time this weekend and the next to fix up a lot of issues. Apologies for the inconvenience, but I have that pesky 9-5 and other life stuff :)

**Comment by LuNoX** [comment]
Pffff, life stuff, who needs that if you can procrastinate by coding stuff

**Comment by PeterCat12** [comment]
Fixed. See the updated documentation for `2.0.0` .
