### ISSUE TITLE
Readme.md typos

### ISSUE THREAD

**Issue by LuNoX** [PeterCat12/pysmash#29]
There's a typo in the first paragraph of Basic Usage: it says "isntance" istead of "instance".
Also there are some problems with the tournaments_show_events block:

- it is not properly formatted (I think it's missing closing code tags)
- response type looks like a list but is actually a dictionary containing a list

**Comment by LuNoX** [comment]
While you did fix the code formatting, there still is a typo in the first paragraph.

**Comment by PeterCat12** [comment]
addressed in 2.0.9
