### ISSUE TITLE
Api updates

### ISSUE THREAD

**Issue by LuNoX** [PeterCat12/pysmash#43]
Just wanted to know if you're gonna bring the wrapper up to date with the Smash.gg API changes or if this repo is gonna be dead.

**Comment by PeterCat12** [comment]
Hey @LuNoX,

No, this repo is not dead. I still use it for a project with Panda Global. I wasn't aware of any API changes with Smash.gg but I have been out of the loop for awhile. What changes are you referring to?

**Comment by PeterCat12** [comment]
@LuNoX I have time this Sunday (10/15/2017) and the weekend after to bring some stuff up to date. If you'd like to write out a list of features/changes you'd like addressed that would be greatly appreciated.

**Comment by LuNoX** [comment]
A few months ago my bot just stopped working without any code changes, so I did some digging and found the pysmash methods to be returning wrong data. When investigating the issue further I found that Smash.gg had started updating their API. I don't know the changes in particular just that they definitely changed some stuff.

**Comment by LuNoX** [comment]
@PeterCat12 I'll try and get a list of features until next week. Kinda busy at the moment :/

It's cool that you're this active though :)

**Comment by PeterCat12** [comment]
@LuNoX Thanks. 

Apologies for never reviewing or addressing your PR. Life just kind of got in the way. I've been planning on a second big push with features soon with my smash4 app which would include changes/updates to this repo.

I will run this repo's test suite and see if anything is super broken. As far as I know though, my smash4 app has been working (mostly) correctly. Smash.gg does have a tendency to change random shit without warning though :(

**Comment by LuNoX** [comment]
@PeterCat12 you did review my PR and told me to go and write tests which I never did cause I'm lazy.

Yeah, sadly.

**Comment by PeterCat12** [comment]
haha damn. Well, I'll look into introducing some CI to this repo over the weekend. See if we can't merge that bad boy in :)

**Comment by PeterCat12** [comment]
Closing issue as the subsequent PR has been closed.
